import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Pueba",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h1>Este es el titulo que se repetira en todas las paginas</h1>
        {children}
      </body>
    </html>
  );
}
